@ASP.NET_Web_API_HostAddress = http://localhost:5200

GET {{ASP.NET_Web_API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST  http://localhost:5200/hello

###

GET http://localhost:5200/product-items
